// app

export const STORE_USER = 'STORE_USER';
export const STORE_WORKBENCHES = 'STORE_WORKBENCHES';
export const STORE_ALL_CATEGORIES = 'STORE_ALL_CATEGORIES';
export const STORE_FILTERED_CATEGORIES = 'STORE_FILTERED_CATEGORIES';
export const STORE_POST_OPTIONS = 'STORE_POST_OPTIONS';

export const LOADING_APP_DATA = 'LOADING_APP_DATA';
export const APP_DATA_READY = 'APP_DATA_READY';



export const CHANGE_APP_STATE_TIME = 'CHANGE_APP_STATE_TIME';
export const START_FETCHING_DATA = 'START_FETCHING_DATA';
export const STOP_FETCHING_DATA = 'STOP_FETCHING_DATA';
export const START_USER_SETTINGS_UPDATE = 'START_USER_SETTINGS_UPDATE';
export const END_USER_SETTINGS_UPDATE = 'END_USER_SETTINGS_UPDATE';
export const UPDATE_USER_SETTINGS = 'UPDATE_USER_SETTINGS';
export const RESET_USER_SETTINGS = 'RESET_USER_SETTINGS';
export const GET_POST_OPTIONS = 'GET_POST_OPTIONS';
export const UPDATE_ROUTER_INFO = 'UPDATE_ROUTER_INFO';

// errors
export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// filter
export const INIT_FILTER = 'INIT_FILTER';
export const CHANGE_CUSTOM_FILTER = 'CHANGE_CUSTOM_FILTER';
export const CHANGE_PRIORITY = 'CHANGE_PRIORITY';
export const CHANGE_WORKBENCH = 'CHANGE_WORKBENCH';
export const UPDATE_FILTER_SETTINGS = 'UPDATE_FILTER_SETTINGS';
export const SAVE_FILTER_CHANGES = 'SAVE_FILTER_CHANGES';

// posts 
export const FETCHING_POSTS = 'FETCHING_POSTS';
export const POSTS_LOADED = 'POSTS_LOADED';
export const UPDATE_POSTS = 'UPDATE_POSTS';
export const OPEN_TABLE_POST = 'OPEN_TABLE_POST';
export const CLOSE_TABLE_POST = 'CLOSE_TABLE_POST';
export const IS_NEW_POST_FORM = 'IS_NEW_POST_FORM';
export const IS_DIRTY_POST_FORM = 'IS_DIRTY_POST_FORM';
// -----------
// export const GET_POSTS = 'GET_POSTS';
// export const GET_POSTS_DEFAULT = 'GET_POSTS_DEFAULT';
// export const GET_POSTS_BY_CATEGORY = 'GET_POSTS_BY_CATEGORY';
// export const GET_POSTS_WEEK = 'GET_POSTS_WEEK';


//push messages
export const FETCHING_PUSH_MESSAGES = 'FETCHING_PUSH_MESSAGES';
export const PUSH_MESSAGES_LOADED = 'PUSH_MESSAGES_LOADED';
export const GET_PUSH_MESSAGES = 'GET_PUSH_MESSAGES';
export const UPDATE_PUSH_MESSAGES = 'UPDATE_PUSH_MESSAGES';
export const SET_NOT_SUPPORTED_FILTER = 'SET_NOT_SUPPORTED_FILTER';